### ISSUE TITLE
Deleting the iCloud store

### ISSUE THREAD

**Issue by lhunath** [alekseyn/iCloudStoreManager#5]
When deleting the iCloud store, we should use a coordinated operation.  See the last paragraph of:

https://developer.apple.com/library/prerelease/ios/#documentation/General/Conceptual/iCloudDesignGuide/Chapters/DesignForCoreDataIniCloud.html#//apple_ref/doc/uid/TP40012094-CH3-SW1

Perhaps this operation should be made available via the //TODO method -deleteStoreForUUID:, or some other method that isn't guarded by "TEST PURPOSES ONLY, DO NOT USE IN PRODUCTION" warnings and flags.

**Comment by alekseyn** [comment]
I originally included the delete functionality for test purposes only, so I wasn't too concerned about coordination problems with something that I wasn't planning to make available in a production release of my app. I'm not convinced using a NSFileCoordinator is required for the database since it is in a .nosync folder. But it's probably warranted for the Data/<UUID> directory. I don't have any time to implement it right now but I would be happy to test and merge anything you come up with. BTW, my new iPad seems to be working better lately.
